export const responses = {
	accessDeniedOwner: 'Тільки власник може змінювати або видаляти запис',
	unauthorized: {
		accessDenied: 'Доступ заборонено. Потрібна авторизація.',
		invalidOrExpiredToken: 'Невірний або термін дії токена сплив.',
	},
	success: {
		userCreated: 'Користувача успішно створено.',
		userUpdated: 'Дані користувача успішно оновлені.',
		codeSent: 'Код підтвердження надіслано на вашу електронну пошту.',
		hallCreated: 'Зал успішно створено.',
		hallUpdated: 'Дані залу успішно оновлені.',
		hallDeleted: 'Зал успішно видалено.',
	},
	error: {
		invalidEmail: 'Невірна адреса електронної пошти.',
		invalidCode: 'Невірний код підтвердження.',
		codeExpired: 'Термін дії коду підтвердження минув.',
		invalidExpiredCode:
			'Невірний код підтвердження або термін дії коду підтвердження минув',
		userNotFound: 'Користувача з такою електронною поштою не знайдено.',
		userExists: 'Користувач з такою електронною поштою вже існує.',
		hallNotFound: 'Зал не знайдено.',
		hallNotAuthorized: 'У вас немає прав для редагування цього залу.',
		internalError: 'Виникла помилка на сервері. Спробуйте ще раз.',
		errorImageNotProvided: 'Зображення не надано',
		imageUploadFailed: 'Не вдалося завантажити зображення',
		queryIsRequired: "Параметр запиту обов'язковим",
		sectionsIdsIsRequired: "Обов'язкові ідентифікатори розділів",
		sectionNotFound: 'Одну або кілька секцій не знайдено',
		subscriptionNotFound: 'Підписку не знайдено',
		memberNotFound: 'Учасника не знайдено',
		memberSubscriptionsNotFound: 'Членство не знайдено',
		sectionNotBelongHall: 'Деякі зали не належать поточному користувачеві',
	},
	validation: {
		emailRequired: 'Поле "Електронна пошта" є обов\'язковим.',
		codeRequired: 'Поле "Код підтвердження" є обов\'язковим.',
		hallNameRequired: 'Поле "Назва залу" є обов\'язковим.',
		hallNameLength: 'Назва залу повинна бути від 3 до 255 символів.',
		codeLength: 'Код підтвердження повинен містити рівно 8 символів.',
		verificationCodeRequired: "Код підтвердження є обов'язковим.",
		hallNameMin: 'Назва залу повинна бути не менше 3 символів.',
		hallNameMax: 'Назва залу повинна бути не більше 255 символів.',
		hallNameRequired: "Назва залу є обов'язковою.",
	},
}
